# application.yml
spring:
  application:
    name: user-service
  config:
    import: configserver:http://localhost:8888/ # This is the crucial line
  cloud:
    config:
      profile: local # Specifies the profile(s) to fetch from the config server

# Your other application-specific properties
server:
  address: localhost
  port: 8086


#  datasource:
#    url: jdbc:postgresql://localhost:5432/UserService
#    driver-class-name: org.postgresql.Driver
#    username: ecommerceUser
#    password: user1234
#  jpa:
#    database-platform: org.hibernate.dialect.PostgreSQLDialect