server:
  servlet:
    context-path: /
  port: 8888

spring:
  application:
    name: config-server
  #  profiles:
  #    active: native, local
  #    include: native
  cloud:
    config:
      server:
        native:
          search-locations: classpath:config/ # This means config server looks for files in 'src/main/resources/config/'
  #        prefix: /config
  jpa:
    hibernate:
      ddl-auto: update

management:
  endpoints:
    web:
      exposure:
        include: '*'
  endpoint:
    health:
      enabled: true
      show-details: always
    info:
      enabled: true
    metrics:
      enabled: true
    refresh:
      enabled: true
    env:
      show-values: always
